function Scenario3figure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 06-Apr-2020 11:37:51

% Create figure
figure1 = figure;

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1.5);
set(plot1(1),'Color',[0 0.5 0]);
set(plot1(2),'Color',[0 0 1]);
set(plot1(3),'Color',[1 0 0]);
set(plot1(4),'Color',[0.5 0.5 0.5]);
set(plot1(5),'LineWidth',2,'Color',[0 0 0]);

% Create ylabel
ylabel('Observed');

% Create xlabel
xlabel('Day');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 365]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontWeight','bold');
% Create textbox
annotation(figure1,'textbox',...
    [0.33 0.33 0.14 0.046],...
    'String',{'Full lockdown'},...
    'FontWeight','bold',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.511 0.77 0.12 0.046],...
    'Color',[1 0 0],...
    'String',{'Full release'},...
    'FontWeight','bold',...
    'EdgeColor','none');

% Create textarrow
annotation(figure1,'textarrow',[0.68 0.63],...
    [0.45 0.33],'Color',[0 0 1],...
    'String',{'E lockdown'},...
    'LineWidth',2,...
    'FontWeight','bold');

% Create textarrow
annotation(figure1,'textarrow',[0.74 0.64],...
    [0.26 0.20],'Color',[0 0.50 0],...
    'String',{'YE lockdown'},...
    'LineWidth',2,...
    'FontWeight','bold');

